version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: brginx
    volumes:
      - ./server.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/dist:/usr/share/nginx/html
    ports:
      - 8081:8081
